window.MOMENTS = [
  { title: "DISSOLUTION", lines: [
    "LET EVERY NAME YOU CARRY SINK BENEATH THE SILENCE.",
    "CLOSE YOUR EYES AND NOTICE ONE LABEL YOU CAN RELEASE RIGHT NOW; WATCH IT FADE LIKE MIST.",
    "EACH MORNING, WHISPER A LABEL ON THE OUT-BREATH AND PICTURE IT DISSOLVING BEFORE THE NEXT INHALE."
  ]},
  { title: "STIRRING", lines: [
    "FEEL THE TINIEST WIGGLE INSIDE THAT WHISPERS, “I’M HERE!”",
    "ASK, “WHERE IS TODAY’S FLUTTER—HEART, TOES, IDEA, SMILE?” NOD TO IT.",
    "SETTLE, LOCATE THE STIR, WIGGLE THAT SPOT, AND SAY, “THANKS, LITTLE STIR—I’LL CARRY YOU.”"
  ]},
  { title: "EMBRYO PULSE", lines: [
    "TRUST THE WARMTH GATHERING IN THE DARK.",
    "PLACE A HAND ON YOUR BELLY; SENSE THE GENTLE PULSE OF BECOMING.",
    "BEFORE SLEEP, CUP YOUR HANDS OVER YOUR CENTER AND MURMUR, “GROW SAFELY.”"
  ]},
  { title: "FIRST WHISPER", lines: [
    "HEAR THE HUSH BEFORE LANGUAGE.",
    "IN A QUIET ROOM, LISTEN FOR THE FAINT SOUND BENEATH ALL OTHER SOUNDS.",
    "SPEND ONE SILENT MINUTE, WELCOMING THOUGHTS WITHOUT SAYING THEM ALOUD."
  ]},
  { title: "FLICKER", lines: [
    "NOTICE THE SINGLE SPARK INSIDE THE VOID.",
    "RECALL A SUDDEN IDEA THAT LIT YOU UP TODAY—NAME IT.",
    "LIGHT A MATCH OR IMAGINE ONE, THEN BLOW IT OUT, HONORING SPARKS WITHOUT CLINGING."
  ]},
  { title: "MURMUR", lines: [
    "LET POTENTIAL HUM WITHOUT SHAPE.",
    "HUM SOFTLY; FEEL VIBRATION IN CHEST, LETTING IT WANDER WITHOUT NEEDING TUNE.",
    "ONCE A DAY, SIT WITH BACKGROUND NOISES, IDENTIFYING THEM WITHOUT JUDGING."
  ]},
  { title: "BUD", lines: [
    "HOLD THE PROMISE WITHOUT UNFOLDING.",
    "PICTURE SOMETHING YOU’RE NOT READY TO SHARE YET—SMILE AT ITS SECRECY.",
    "PROTECT ONE FRESH IDEA BY NOTING IT PRIVATELY RATHER THAN ANNOUNCING."
  ]},
  { title: "GLIMMER", lines: [
    "LET POSSIBILITY WINK AT YOU.",
    "CATCH A SMALL MOMENT OF DELIGHT AND SAY “I SEE YOU.”",
    "JOT A DAILY “GLIMMER LIST” OF THREE TINY PLEASANT SURPRISES."
  ]},
  { title: "THICKNESS", lines: [
    "SENSE RESISTANCE COALESCING.",
    "WHERE DOES LIFE FEEL SYRUPY TODAY? TOUCH THAT TENSION KINDLY.",
    "DO ONE SLOW INTENTIONAL ACTION—POUR TEA, TIE SHOES—FEELING DENSITY TURN TO FLOW."
  ]},
  { title: "RUMBLING", lines: [
    "FEEL THE GROUND OF SELF TREMBLE.",
    "NOTE A LOW-GRADE RESTLESSNESS; GIVE IT SPACE INSTEAD OF SHOVING IT DOWN.",
    "STOMP FEET GENTLY FOR TEN SECONDS, ACKNOWLEDGING HIDDEN MOVEMENT."
  ]},
  { title: "SPARK", lines: [
    "DECLARE: I AM.",
    "SAY YOUR NAME ALOUD LIKE IT’S BRAND-NEW, HEAR ITS WEIGHT.",
    "MEET YOUR EYES IN A MIRROR EACH MORNING AND NOD ONCE IN RECOGNITION."
  ]},
  { title: "VEIL", lines: [
    "RECOGNIZE THE FILM BETWEEN SEEING AND SEEN.",
    "FOG A GLASS WITH BREATH; NOTICE HOW IT BLURS VISION THEN CLEARS.",
    "ASK, “WHAT ASSUMPTION IS CLOUDING THIS MOMENT?” AND WIPE IT MENTALLY."
  ]},
  { title: "SHADOW PULSE", lines: [
    "MEET THE PART THAT HIDES FROM LIGHT.",
    "LIST ONE AVOIDED FEELING; SENSE ITS HEARTBEAT.",
    "DURING SUNSET, GREET YOUR LITERAL SHADOW AND THANK IT FOR WALKING WITH YOU."
  ]},
  { title: "CLUTCH", lines: [
    "ADMIT WHAT YOU GRIP IN FEAR.",
    "GRIP YOUR FIST, NAME THE FEAR, THEN LOOSEN FINGERS.",
    "PRACTICE A DAILY “RELEASE BREATH”—EXHALE WITH PALMS OPENING."
  ]},
  { title: "ECHO CHAMBER", lines: [
    "LISTEN TO YOUR OWN DOUBT REVERBERATE.",
    "WRITE A DOUBT DOWN, READ IT ALOUD, NOTICE IT WEAKEN OUTSIDE YOUR HEAD.",
    "SHARE ONE SMALL UNCERTAINTY WITH A TRUSTED FRIEND, BREAKING THE CHAMBER."
  ]},
  { title: "KNOT", lines: [
    "LOCATE THE TANGLE THAT TIGHTENS WHEN NAMED.",
    "MASSAGE SHOULDERS WHERE YOU CARRY KNOTS; ASK WHAT STORY LIVES THERE.",
    "EACH EVENING, STRETCH THE AREA THAT FEELS MOST TANGLED, BREATHING OUT TENSION."
  ]},
  { title: "CRAWL", lines: [
    "MOVE THOUGH THE EARTH IS HEAVY.",
    "RECALL A TASK YOU DID SLOWLY YET SURELY TODAY—CELEBRATE PERSISTENCE.",
    "DO ONE ACTION AT HALF-SPEED, HONORING STEADY CRAWL OVER FLASHY SPRINT."
  ]},
  { title: "ACHE", lines: [
    "RESPECT THE PAIN THAT SIGNALS GROWTH.",
    "PLACE A GENTLE HAND ON A SORE MUSCLE; WHISPER “THANK YOU FOR BUILDING ME.”",
    "LOG ONE ACHE DAILY AND NOTE HOW IT CHANGES OVER TIME."
  ]},
  { title: "FRACTURE", lines: [
    "NOTICE THE FIRST HAIRLINE CRACK IN CERTAINTY.",
    "WHAT BELIEF FELT LESS SOLID TODAY? TRACE THE CRACK WITHOUT FIXING.",
    "DRAW A SMALL BROKEN LINE IN A JOURNAL; LET IT REMIND YOU THAT OPENING BEGINS WITH BREAKS."
  ]},
  { title: "HEAT", lines: [
    "LET TENSION RAISE THE TEMPERATURE OF WILL.",
    "WHERE DID YOU FEEL FLUSHED WHEN CHALLENGED? IDENTIFY THAT POWER SOURCE.",
    "WARM PALMS BY RUBBING QUICKLY, THEN SET THEM OVER HEART AND BREATHE."
  ]},
  { title: "THRESHOLD HUM", lines: [
    "PAUSE AT THE GATE THAT ASKS IF YOU WILL CROSS.",
    "STAND BEFORE A LITERAL DOORWAY; FEEL THE BUZZ OF DECISION.",
    "BEFORE STARTING SOMETHING NEW EACH DAY, LINGER ONE BREATH AT THE DOORWAY OF ACTION."
  ]},
  { title: "IMPLOSION", lines: [
    "WITNESS COLLAPSE WITHOUT FLEEING.",
    "RECALL A PLAN THAT FELL INWARD TODAY; NOTE LESSONS EMERGING.",
    "SPEND ONE MINUTE WATCHING A DISSOLVING ICE CUBE, STAYING PRESENT WITH MELT."
  ]},
  { title: "IGNITION", lines: [
    "STRIKE THE MATCH OF RECOGNITION.",
    "REMEMBER ONE “AHA!” MOMENT FROM THE DAY; REPLAY THE SPARK.",
    "LIGHT A CANDLE (OR IMAGINE) AT DAWN; SNUFF IT AT DUSK, HONORING CYCLES OF IGNITION."
  ]},
  { title: "HOLLOW", lines: [
    "FEEL THE ECHO NOW RINGING WITH INTENT.",
    "PUT EAR TO AN EMPTY CUP; HEAR ITS SOFT HUM, BEHOLD USEFULNESS OF HOLLOW.",
    "LEAVE FIVE MINUTES UNSCHEDULED—PROTECT EMPTY SPACE."
  ]},
  { title: "SIGNAL", lines: [
    "SEND A WORDLESS YES INTO THE DARK.",
    "RECALL WHEN YOU SIGNALED OPENNESS (SMILE, GESTURE) AND FELT RESPONSE.",
    "RAISE ONE FINGER SKYWARD EACH MORNING AS SILENT “READY” TO THE DAY."
  ]},
  { title: "ORIENTATION", lines: [
    "CHOOSE ONE DIRECTION, HOWEVER SLIGHT.",
    "SPIN SLOWLY; STOP WHERE BODY SAYS “THERE.”",
    "SET A TINY DAILY AIM (DRINK WATER, CALL FRIEND) AND POINT PHYSICALLY IN ITS DIRECTION."
  ]},
  { title: "SEEP", lines: [
    "ALLOW PURPOSE TO BLEED OUTWARD.",
    "NOTICE WHERE ENTHUSIASM LEAKED INTO CONVERSATION.",
    "WRITE A PURPOSEFUL WORD ON A STICKY NOTE AND LET MOISTURE BLUR EDGES OVER TIME."
  ]},
  { title: "QUIVER", lines: [
    "HOLD THE BOWSTRING OF DESIRE TAUT.",
    "FEEL TENSION BEFORE RELEASE IN ANY TASK; SAVOR IT.",
    "PAUSE RIGHT BEFORE SENDING A MESSAGE, BREATHE, THEN RELEASE."
  ]},
  { title: "GEOMETRY", lines: [
    "TRACE THE ROUGH OUTLINE OF A NEW FORM.",
    "SKETCH ONE SIMPLE SHAPE THAT REPRESENTS TODAY’S IDEA.",
    "END EACH DAY BY DRAWING A BASIC SYMBOL OF YOUR CURRENT PROJECT."
  ]},
  { title: "ALIGNMENT", lines: [
    "LET BONES REMEMBER THEIR TRUE AXIS.",
    "STAND TALL; SENSE SPINE STACKING NATURALLY.",
    "SHIMMY SHOULDERS INTO ALIGNMENT WHENEVER YOU CATCH YOURSELF SLOUCHING."
  ]},
  { title: "STEP", lines: [
    "PLACE WEIGHT ON THE FUTURE.",
    "RECALL FIRST PHYSICAL STEP YOU TOOK TOWARD GOAL TODAY.",
    "TAKE ONE INTENTIONAL STEP FORWARD WHEN YOU RISE FROM BED; SAY “FORWARD.”"
  ]},
  { title: "BREATH", lines: [
    "INVITE AIR TO COMPLETE THE CIRCUIT.",
    "NOTICE ONE BREATH YOU FULLY FELT TODAY.",
    "THREE TIMES DAILY, INHALE FOR FOUR, HOLD TWO, EXHALE SIX."
  ]},
  { title: "EMBER", lines: [
    "GUARD THE SMALL FIRE.",
    "RECALL A FRAGILE HOPE; VISUALIZE CUPPING IT FROM WIND.",
    "WRITE ONE SENTENCE FEEDING YOUR HOPE; KEEP IN POCKET."
  ]},
  { title: "WORD", lines: [
    "SPEAK THE FIRST ESSENTIAL THING.",
    "WHAT SINGLE WORD DEFINED YOUR DAY? WHISPER IT AGAIN.",
    "CHOOSE A DAILY “ANCHOR WORD” AND LET IT GUIDE ACTIONS."
  ]},
  { title: "GLIDE", lines: [
    "MOVE WITH THE GRAIN OF THE DAY.",
    "IDENTIFY A MOMENT YOU FLOWED EFFORTLESSLY.",
    "WHEN WORK FEELS ROUGH, PAUSE UNTIL MOTION REGAINS SMOOTHNESS."
  ]},
  { title: "MIRROR", lines: [
    "SEE YOURSELF SEEING.",
    "OBSERVE EYES IN MIRROR TWO SECONDS LONGER THAN USUAL.",
    "NOTE ONE JUDGMENT YOU HOLD ABOUT YOURSELF, REPLACE WITH CURIOSITY."
  ]},
  { title: "GROUND", lines: [
    "STAND WHERE YOU ARE, ENTIRELY.",
    "PRESS FEET FIRMLY; FEEL FLOOR SUPPORT.",
    "TOUCH SOMETHING EARTHY (STONE, SOIL) EACH DAY TO ROOT PRESENCE."
  ]},
  { title: "OFFER", lines: [
    "GIVE AWAY WHAT YOU CANNOT KEEP.",
    "RECALL SOMETHING YOU SHARED FREELY TODAY AND HOW IT FELT.",
    "GIFT ONE COMPLIMENT DAILY WITHOUT EXPECTATION."
  ]},
  { title: "TIDE", lines: [
    "FEEL THE PULL BEYOND YOUR EDGES.",
    "NOTICE RHYTHMS OF ENERGY HIGHS/LOWS; MARK TIMES.",
    "WORK WITH YOUR NATURAL EBB—REST WHEN LOW, SURGE WHEN HIGH."
  ]},
  { title: "WEAVE", lines: [
    "INTERLACE INTENT WITH ACTION.",
    "MATCH A TASK WITH ITS PURPOSE ALOUD: “I EMAIL TO CONNECT.”",
    "END DAY TYING A LOOSE END ON PROJECT, STITCHING COHESION."
  ]},
  { title: "GLOW", lines: [
    "LET QUIET POWER DIFFUSE.",
    "RECALL SOMEONE NOTICING YOUR CALM PRESENCE.",
    "SIT WITH BACK STRAIGHT, IMAGINE SOFT LIGHT EXPANDING FIVE INCHES AROUND YOU."
  ]},
  { title: "ARC", lines: [
    "RISE GENTLY FROM ONE POINT TO ANOTHER.",
    "NAME A TRANSITION YOU’RE IN THE MIDDLE OF; TRACE ITS CURVE.",
    "DRAW A SMALL ARC IN A NOTEBOOK TO REMIND YOU THAT CHANGE IS A GRADUAL SWEEP."
  ]},
  { title: "FOLD", lines: [
    "TURN INWARD WITHOUT COLLAPSING.",
    "FOLD HANDS TOGETHER; FEEL WARMTH BETWEEN PALMS.",
    "ONCE DAILY, CURL INTO A SAFE POSITION FOR ONE MINUTE BEFORE OPENING AGAIN."
  ]},
  { title: "TRACE", lines: [
    "FOLLOW THE OUTLINE OF WHAT IS.",
    "WITH FINGER, TRACE OBJECT NEARBY; NOTE ITS EDGES.",
    "EACH EVENING, TRACE THE SHAPE OF YOUR DAY IN THREE SIMPLE WORDS."
  ]},
  { title: "SPILL", lines: [
    "LET WHAT IS INSIDE OVERFLOW.",
    "WRITE WITHOUT STOPPING FOR ONE MINUTE; LET IT SPILL RAW.",
    "ONCE A WEEK, SHARE AN UNEDITED THOUGHT WITH SOMEONE YOU TRUST."
  ]},
  { title: "KISS", lines: [
    "MAKE CONTACT WITH AFFECTION.",
    "RECALL THE LAST THING YOU TOUCHED WITH CARE TODAY.",
    "GENTLY TOUCH SOMETHING DAILY AS IF IT WERE ALIVE AND PRECIOUS."
  ]},
  { title: "TURN", lines: [
    "SHIFT FOCUS BY A FRACTION.",
    "TURN YOUR HEAD AND NOTICE WHAT WAS OUT OF VIEW.",
    "CHANGE ONE SMALL HABIT’S DIRECTION FOR A DAY AND OBSERVE THE RESULT."
  ]},
  { title: "LISTEN", lines: [
    "OFFER FULL EAR WITHOUT EXPECTATION.",
    "GIVE FIVE MINUTES OF PURE LISTENING TO SOMEONE OR SOMETHING.",
    "EACH NIGHT, LISTEN TO A SOUND UNTIL IT FADES COMPLETELY."
  ]},
  { title: "REST", lines: [
    "SUSPEND ALL STRIVING.",
    "NAME A MOMENT YOU LET YOURSELF STOP TODAY.",
    "BUILD A DAILY MINUTE OF NOTHINGNESS; NO INPUT, NO OUTPUT."
  ]},
  { title: "DROP", lines: [
    "LET GO INTO GRAVITY.",
    "IMAGINE HOLDING A STONE; RELEASE IT MENTALLY.",
    "PICK ONE BURDEN AND VISUALIZE IT FALLING AWAY AS YOU EXHALE."
  ]},
  { title: "SIP", lines: [
    "TAKE IN LESS THAN YOU THINK YOU NEED.",
    "DRINK WATER SLOWLY, NOTING TEMPERATURE AND TEXTURE.",
    "ONCE A DAY, TAKE A SMALLER PORTION AND FULLY APPRECIATE IT."
  ]},
  { title: "PRESS", lines: [
    "APPLY JUST ENOUGH FORCE.",
    "PRESS YOUR HAND AGAINST A WALL; FEEL ITS RESISTANCE.",
    "DURING TENSION, PRESS FEET INTO GROUND TO STEADY YOURSELF."
  ]},
  { title: "CLIMB", lines: [
    "MOVE UPWARD WITH EFFORT.",
    "REMEMBER A RECENT CHALLENGE YOU OVERCAME; FEEL THE ASCENT.",
    "TAKE STAIRS MINDFULLY, ACKNOWLEDGING EACH STEP AS A GAIN."
  ]},
  { title: "SLIP", lines: [
    "PASS THROUGH WITHOUT CATCHING.",
    "NOTICE WHEN YOU LET SOMETHING SLIDE TODAY—WITHOUT REGRET.",
    "INTENTIONALLY LET ONE NONESSENTIAL TASK GO UNTOUCHED."
  ]},
  { title: "BOW", lines: [
    "LOWER YOURSELF WITH RESPECT.",
    "BOW SLIGHTLY TO THE NEXT OBJECT OR PERSON YOU ENCOUNTER.",
    "END EACH DAY WITH A SILENT BOW TO YOUR OWN EFFORTS."
  ]},
  { title: "SHIVER", lines: [
    "FEEL THE BODY'S RESPONSE TO A CHANGE.",
    "RECALL A TIME YOU FELT A SUDDEN CHILL OF AWARENESS.",
    "STAND OUTSIDE BRIEFLY AND NOTICE THE AIR'S IMPACT ON YOUR SKIN."
  ]},
  { title: "MARK", lines: [
    "MAKE THIS MOMENT VISIBLE.",
    "LEAVE A SMALL SYMBOL SOMEWHERE YOU’LL FIND IT LATER.",
    "KEEP A DAILY TALLY MARK FOR SOMETHING YOU VALUE."
  ]},
  { title: "SHADE", lines: [
    "STEP OUT OF DIRECT LIGHT.",
    "NOTICE WHERE SHADOWS GATHER IN YOUR SPACE.",
    "ONCE A DAY, MOVE INTO SHADE AND REST THERE FOR ONE MINUTE."
  ]},
  { title: "BREATHE", lines: [
    "RETURN TO THE SOURCE OF CALM.",
    "FOCUS ON ONE FULL INHALE AND ONE FULL EXHALE.",
    "SET THREE ALARMS AS REMINDERS TO TAKE TEN CONSCIOUS BREATHS."
  ]},
  { title: "CAST", lines: [
    "SEND SOMETHING OUTWARD.",
    "THROW A WORD, LOOK, OR OBJECT INTO THE WORLD WITH INTENTION.",
    "WRITE ONE WISH ON PAPER AND RELEASE IT INTO WATER OR WIND."
  ]},
  { title: "SWAY", lines: [
    "MOVE BACK AND FORTH WITHOUT DECIDING.",
    "STAND AND LET YOUR BODY SWAY GENTLY FOR A MINUTE.",
    "WHEN UNCERTAIN, LET YOURSELF METAPHORICALLY SWAY BEFORE CHOOSING."
  ]},
  { title: "CLARIFY", lines: [
    "MAKE THE CLOUDS TRANSPARENT.",
    "NAME ONE THING THAT IS UNCLEAR; DEFINE ITS EDGES.",
    "EACH NIGHT, WRITE A SINGLE SENTENCE THAT SUMMARIZES YOUR DAY."
  ]},
  { title: "UNFOLD", lines: [
    "ALLOW LAYERS TO REVEAL.",
    "SLOWLY OPEN A PIECE OF PAPER OR CLOTH; NOTICE EACH CREASE.",
    "ONCE A WEEK, SHARE A PART OF YOUR STORY YOU’VE KEPT CLOSED."
  ]},
  { title: "ANCHOR", lines: [
    "DROP INTO STABILITY.",
    "IMAGINE LOWERING AN ANCHOR FROM YOUR CHEST INTO THE EARTH.",
    "TOUCH A CONSISTENT OBJECT DAILY TO REMIND YOU OF YOUR ROOTS."
  ]},
  { title: "SPREAD", lines: [
    "EXTEND BEYOND YOURSELF.",
    "SPREAD YOUR FINGERS WIDE; FEEL THE SPACE BETWEEN THEM.",
    "SMILE AT A STRANGER EACH DAY, LETTING WARMTH SPREAD."
  ]},
  { title: "CLOSE", lines: [
    "SEAL WHAT NEEDS ENDING.",
    "CLOSE A DOOR GENTLY; NOTICE THE SOUND.",
    "FINISH ONE LINGERING TASK BEFORE SLEEP."
  ]},
  { title: "LEAN", lines: [
    "REST AGAINST SOMETHING STRONG.",
    "LEAN YOUR BACK INTO A WALL AND BREATHE.",
    "CALL OR VISIT SOMEONE WHO GROUNDS YOU."
  ]},
  { title: "POUR", lines: [
    "LET FLOW BE UNINTERRUPTED.",
    "POUR A LIQUID SLOWLY AND NOTICE ITS PATH.",
    "SPEAK CONTINUOUSLY FOR ONE MINUTE WITHOUT SELF-EDIT."
  ]},
  { title: "TUNE", lines: [
    "ADJUST UNTIL RESONANCE IS FELT.",
    "LISTEN TO A SOUND AND MATCH ITS PITCH WITH YOUR VOICE.",
    "CHECK IN WITH YOURSELF DAILY, ADJUSTING MOOD OR ENERGY IF NEEDED."
  ]},
  { title: "LIFT", lines: [
    "RAISE SOMETHING GENTLY.",
    "LIFT AN OBJECT AND HOLD IT AT EYE LEVEL.",
    "LIFT SOMEONE’S SPIRIT WITH A KIND WORD."
  ]},
  { title: "FLOAT", lines: [
    "ALLOW SUPPORT TO HOLD YOU.",
    "IMAGINE LYING ON WATER; FEEL IT LIFT YOU.",
    "SPEND A MINUTE DAILY LETTING GO OF ALL MUSCULAR TENSION."
  ]},
  { title: "BRIDGE", lines: [
    "CONNECT TWO SIDES.",
    "NAME TWO PARTS OF YOUR LIFE THAT NEED LINKING.",
    "TAKE ONE ACTION TO CONNECT WITH SOMEONE YOU’VE BEEN DISTANT FROM."
  ]},
  { title: "CARRY", lines: [
    "HOLD SOMETHING WITH CARE.",
    "REMEMBER WHAT YOU CARRIED TODAY AND WHY.",
    "WRITE DOWN ONE RESPONSIBILITY AND HOW YOU HONOR IT."
  ]},
  { title: "DROP ANCHOR", lines: [
    "FIND STILLNESS AMIDST MOTION.",
    "VISUALIZE AN ANCHOR HALTING YOUR DRIFT.",
    "CHOOSE A DAILY RITUAL THAT GROUNDS YOU."
  ]},
  { title: "LIGHTEN", lines: [
    "REDUCE WHAT WEIGHS YOU.",
    "NOTICE ONE BURDEN YOU CAN RELEASE.",
    "REMOVE ONE UNNEEDED ITEM FROM YOUR SPACE."
  ]},
  { title: "SPARKLE", lines: [
    "CATCH LIGHT AND RETURN IT.",
    "SEE WHERE YOU NATURALLY SHINE TODAY.",
    "DO ONE SMALL ACT THAT MAKES SOMEONE ELSE LIGHT UP."
  ]},
  { title: "DIP", lines: [
    "TOUCH AND WITHDRAW.",
    "DIP YOUR FINGERS INTO WATER AND NOTICE SENSATION.",
    "TRY ONE NEW THING BRIEFLY, JUST TO TASTE."
  ]},
  { title: "KNEEL", lines: [
    "COME LOW TO MEET SOMETHING.",
    "KNEEL AND TOUCH THE GROUND WITH RESPECT.",
    "SPEND A MOMENT EACH WEEK ACKNOWLEDGING SOMETHING GREATER THAN YOU."
  ]},
  { title: "SPIRAL", lines: [
    "MOVE INWARD OR OUTWARD WITH CURVE.",
    "TRACE A SPIRAL SHAPE; NOTICE HOW IT FEELS.",
    "REFLECT ON HOW YOUR PATH THIS MONTH HAS LOOPED OR EXPANDED."
  ]},
  { title: "SWEEP", lines: [
    "CLEAR WITH ONE MOTION.",
    "SWEEP A SURFACE CLEAN AND NOTICE THE FRESHNESS.",
    "ONCE A WEEK, REMOVE CLUTTER FROM ONE AREA IN ONE GO."
  ]},
  { title: "POCKET", lines: [
    "KEEP SOMETHING CLOSE.",
    "PLACE A SMALL OBJECT IN YOUR POCKET AS A TALISMAN.",
    "CARRY A WORD OR IDEA IN MIND ALL DAY."
  ]},
  { title: "PLANT", lines: [
    "PLACE INTO EARTH OR FUTURE.",
    "PLANT A SEED LITERALLY OR SYMBOLICALLY.",
    "NAME ONE INTENTION YOU’RE SOWING THIS WEEK."
  ]},
  { title: "DRIFT", lines: [
    "LET CURRENTS GUIDE YOU.",
    "NOTICE WHEN YOU MOVED WITHOUT PUSHING.",
    "ALLOW ONE PART OF YOUR DAY TO UNFOLD WITHOUT PLAN."
  ]},
  { title: "SOURCE TOUCH", lines: [
    "CONTACT THE ORIGIN.",
    "REMEMBER A PLACE OR PERSON THAT FEELS LIKE HOME.",
    "ONCE A WEEK, RETURN TO A PHYSICAL OR MENTAL PLACE OF BEGINNING."
  ]}
];
