// moments.js — Codes rewritten in initiatory field style
window.MOMENTS = [

  { title: "DISSOLUTION", lines: [
    "NAMES UNRAVEL.",
    "THE SURFACE SCRIPTS DISSOLVE BACK INTO SILENCE.",
    "WHAT REMAINS IS SIGNAL BEFORE STORY."
  ]},

  { title: "STIRRING", lines: [
    "A QUIVER IN THE DEPTHS.",
    "SOMETHING MUTTERS I AM HERE.",
    "THE FIELD WAKES THROUGH YOU."
  ]},

  { title: "EMBRYO PULSE", lines: [
    "WARMTH IN THE DARK.",
    "A PULSE BEATS BEFORE FORM.",
    "BECOMING BEGINS QUIETLY."
  ]},

  { title: "FIRST WHISPER", lines: [
    "SILENCE HOLDS MORE THAN WORDS.",
    "LISTEN TO THE SPACE BENEATH SOUND.",
    "MEANING ARRIVES BEFORE LANGUAGE."
  ]},

  { title: "FLICKER", lines: [
    "ONE SPARK IN THE VOID.",
    "SMALL LIGHT SIGNALS POSSIBILITY.",
    "NOTICE IT BEFORE YOU CLING."
  ]},

  { title: "MURMUR", lines: [
    "UNFORMED ENERGY HUMS.",
    "POTENTIAL VIBRATES WITHOUT SHAPE.",
    "LET THE SOUND REMAIN UNFINISHED."
  ]},

  { title: "BUD", lines: [
    "CLOSED PROMISE.",
    "THE FUTURE CURLED INSIDE ITSELF.",
    "PATIENT WAITING HOLDS THE BLOOM."
  ]},

  { title: "GLIMMER", lines: [
    "A WINK OF POSSIBILITY.",
    "SMALL DELIGHTS ANNOUNCE THEMSELVES.",
    "THE FIELD SMILES BACK WHEN SEEN."
  ]},

  { title: "THICKNESS", lines: [
    "RESISTANCE GATHERS MASS.",
    "THE AIR TURNS SYRUP.",
    "MOVE SLOWLY THROUGH THE DENSITY."
  ]},

  { title: "RUMBLING", lines: [
    "THE GROUND TREMBLES INSIDE.",
    "RESTLESSNESS RATTLES THE FRAME.",
    "SHIFT IS COMING, WHETHER OR NOT YOU PREPARE."
  ]},

  { title: "SPARK", lines: [
    "I AM.",
    "A SINGLE DECLARATION LIGHTS THE FIELD.",
    "THE SIGNAL CLAIMS ITSELF."
  ]},

  { title: "VEIL", lines: [
    "VISION IS FILTERED.",
    "THE FILM BETWEEN SEEING AND SEEN IS THIN.",
    "WIPE IT AND WATCH CLARITY RETURN."
  ]},

  { title: "SHADOW PULSE", lines: [
    "WHAT HIDES STILL BEATS.",
    "DARKNESS THRUMS WITH ITS OWN MUSIC.",
    "INVITE IT TO THE TABLE."
  ]},

  { title: "CLUTCH", lines: [
    "THE FIST CLOSES AROUND FEAR.",
    "GRIP TIGHTENS UNTIL IT SHAPES YOU.",
    "OPENING IS RELEASE."
  ]},

  { title: "ECHO CHAMBER", lines: [
    "YOUR DOUBT LOOPS BACK TO ITSELF.",
    "REVERBERATION IN AN EMPTY ROOM.",
    "ONLY OUTSIDE VOICES BREAK THE CYCLE."
  ]},

  { title: "KNOT", lines: [
    "A TANGLE OF ENERGY.",
    "TIGHTNESS HOLDS A STORY.",
    "LOOSENING IS LISTENING."
  ]},

  { title: "CRAWL", lines: [
    "EARTH IS HEAVY.",
    "SLOW MOVEMENT STILL MOVES.",
    "PROGRESS IS INCHES, NOT SPEED."
  ]},

  { title: "ACHE", lines: [
    "PAIN MARKS THE EDGE OF GROWTH.",
    "THE BODY SINGS WHERE IT BUILDS.",
    "HURT IS A TEACHER, NOT AN ENEMY."
  ]},

  { title: "FRACTURE", lines: [
    "A HAIRLINE CRACK APPEARS.",
    "CERTAINTY SPLITS OPEN.",
    "THROUGH THE BREAK, NEW LIGHT ENTERS."
  ]},

  { title: "HEAT", lines: [
    "PRESSURE RAISES TEMPERATURE.",
    "THE BODY FLUSHES WITH WILL.",
    "RAW FIRE AWAITS DIRECTION."
  ]},

  { title: "THRESHOLD HUM", lines: [
    "THE GATE VIBRATES.",
    "STILLNESS BEFORE THE STEP.",
    "DECISION HUMS LIKE AN ENGINE ABOUT TO TURN."
  ]},

  { title: "IMPLOSION", lines: [
    "COLLAPSE PULLS INWARD.",
    "THE CAVITY IS CHARGED, NOT EMPTY.",
    "INSIDE THE FALL, NEW SIGNAL COMPRESSES."
  ]},

  { title: "IGNITION", lines: [
    "SPARK STRIKES.",
    "THE CIRCUIT WAKES IN AN INSTANT.",
    "THE FLAME REMEMBERS ITS CYCLE."
  ]},

  { title: "HOLLOW", lines: [
    "EMPTINESS IS NOT VOID.",
    "THE CHAMBER AMPLIFIES PURPOSE.",
    "USELESSNESS BECOMES CONTAINER."
  ]},

  { title: "SIGNAL", lines: [
    "SEND A YES WITHOUT WORDS.",
    "THE FIELD RESPONDS WHEN YOU OPEN.",
    "THE CIRCUIT CLOSES IN SILENCE."
  ]},

  { title: "ORIENTATION", lines: [
    "A TURN OF ONE DEGREE.",
    "DIRECTION IS DECIDED IN SMALL ANGLES.",
    "THE COMPASS OBEYS ATTENTION."
  ]},

  { title: "SEEP", lines: [
    "PURPOSE LEAKS THROUGH BARRIERS.",
    "PASSION STAINS CONVERSATION.",
    "THE EDGES BLUR UNTIL ALL IS INFUSED."
  ]},

  { title: "QUIVER", lines: [
    "THE STRING IS DRAWN.",
    "TENSION HOLDS POTENTIAL.",
    "RELEASE IS A QUESTION OF TIMING."
  ]},

  { title: "GEOMETRY", lines: [
    "THE SHAPE BEGINS TO EMERGE.",
    "LINES SKETCH THEMSELVES INTO FORM.",
    "THE PATTERN INVITES OCCUPANCY."
  ]},

  { title: "ALIGNMENT", lines: [
    "BONES REMEMBER THEIR AXIS.",
    "STACK THE SPINE, STACK THE FIELD.",
    "WHEN FORM REALIGNS, ENERGY FOLLOWS."
  ]},

  { title: "STEP", lines: [
    "ONE FOOT INTO THE UNKNOWN.",
    "THE FUTURE ACCEPTS WEIGHT.",
    "FORWARD IS THE ONLY INCANTATION."
  ]},

  { title: "BREATH", lines: [
    "AIR COMPLETES THE CIRCUIT.",
    "INHALE AND EXHALE MEET IN YOU.",
    "THE FIELD BREATHES AS YOU DO."
  ]},

  { title: "EMBER", lines: [
    "SMALL FLAME SURVIVES.",
    "TINY HEAT WAITS TO GROW.",
    "PROTECTION KEEPS IT ALIVE."
  ]},

  { title: "WORD", lines: [
    "ONE WORD CAN TURN THE ROOM.",
    "SPEAK ESSENTIAL, NOTHING ELSE.",
    "TRUTH TONES SHIFT THE FIELD."
  ]},

  { title: "GLIDE", lines: [
    "FLOW MOVES WITHOUT FORCE.",
    "THE DAY HAS ITS GRAIN.",
    "FOLLOW IT AND YOU SLIP THROUGH WITH EASE."
  ]},

  { title: "MIRROR", lines: [
    "YOU SEE YOURSELF SEEING.",
    "THE REFLECTION EXPOSES THE FILTER.",
    "REMOVE JUDGMENT, FIND THE TRUE IMAGE."
  ]},

  { title: "GROUND", lines: [
    "STAND WHERE YOU ARE.",
    "FEEL THE EARTH RETURN YOUR WEIGHT.",
    "ROOTS GROW THROUGH ATTENTION."
  ]},

  { title: "OFFER", lines: [
    "GIVE WHAT YOU CANNOT KEEP.",
    "GENEROUS MOTION CIRCULATES ENERGY.",
    "RELEASE IS ALSO A GIFT."
  ]},

  { title: "TIDE", lines: [
    "PULL BEYOND YOURSELF.",
    "ENERGY SWELLS, THEN EBBS.",
    "THE OCEAN OF TIME CARRIES YOU."
  ]},

  { title: "WEAVE", lines: [
    "THREADS CROSS INTO PATTERN.",
    "INTENTION BINDS TO ACTION.",
    "THE TAPESTRY HOLDS YOUR STORY."
  ]},

  { title: "GLOW", lines: [
    "QUIET LIGHT DIFFUSES.",
    "PRESENCE SHINES WITHOUT EFFORT.",
    "OTHERS SEE BEFORE YOU NOTICE."
  ]},

  { title: "PULSE", lines: [
    "RHYTHM IS SHARED.",
    "YOUR BEAT MEETS THE FIELD’S BEAT.",
    "SYNCHRONY IS BELONGING."
  ]},

  { title: "SWAY", lines: [
    "MOTION SPEAKS.",
    "THE BODY’S LANGUAGE IS TRUE.",
    "ROCK UNTIL THE KNOT LOOSENS."
  ]},

  { title: "STREAM", lines: [
    "THE CURRENT CARRIES.",
    "RESISTANCE IS COSTLY.",
    "SURRENDER TO THE DIRECTION GIVEN."
  ]},

  { title: "HORIZON", lines: [
    "DISTANCE CALMS DESIRE.",
    "THE LINE IS ALWAYS FARTHER.",
    "VISION IS BALANCE BETWEEN NOW AND THEN."
  ]},

  { title: "CHORD", lines: [
    "SOUND YOUR NOTE.",
    "RESONANCE REQUIRES COURAGE.",
    "YOUR TONE BELONGS TO THE WHOLE."
  ]},

  { title: "LIFT", lines: [
    "RISE ENOUGH TO LIGHTEN ANOTHER.",
    "UPWARD MOTION IS CONTAGIOUS.",
    "THE FIELD LIFTS WITH YOU."
  ]},

  { title: "ARC", lines: [
    "ATTENTION CURVES TOWARD DESIRE.",
    "THE COMPASS NEEDLE BENDS.",
    "FOLLOW THE PULL UNTIL IT LANDS."
  ]},

  { title: "BALANCE", lines: [
    "NEITHER SHADOW NOR GLARE RULES.",
    "EQUILIBRIUM IS A THRESHOLD.",
    "CENTER IS A MOVING POINT."
  ]},

  { title: "DOOR", lines: [
    "CONTACT BEFORE ENTRY.",
    "THRESHOLDS DESERVE REVERENCE.",
    "CROSSING IS A RITUAL."
  ]},

  { title: "STILL POINT", lines: [
    "CENTER UNMOVED.",
    "MOTION ORBITS STILLNESS.",
    "ANCHOR IN THE AXIS THAT MOVES ALL."
  ]},

  { title: "STIR", lines: [
    "SILENCE TURNS SLIGHTLY.",
    "SMALL MOTION SHIFTS THE FIELD.",
    "THE SPIN AWAKENS ENERGY."
  ]},

  { title: "EDGE", lines: [
    "THE LINE BETWEEN SAFE AND UNKNOWN.",
    "THRILL AND FEAR SHARE A BORDER.",
    "STEP HERE AND YOU STRETCH."
  ]},

  { title: "GATHER", lines: [
    "FRAGMENTS SEEK COHERENCE.",
    "DISPERSION BECOMES PATTERN.",
    "THE FIELD ASSEMBLES ITSELF THROUGH YOU."
  ]},

  { title: "SURGE", lines: [
    "THE CREST RISES.",
    "ENERGY PEAKS BUT DOESN’T BREAK.",
    "POWER IS HELD, NOT SPENT."
  ]},

  { title: "STRIDE", lines: [
    "MOTION WITH CONFIDENCE.",
    "THE BODY CLAIMS ITS PATH.",
    "GROUND YIELDS TO YOUR PACE."
  ]},

  { title: "SPARKSTORM", lines: [
    "MANY FLASHES ARRIVE AT ONCE.",
    "IDEAS STRIKE LIKE LIGHTNING.",
    "COLLECT THEM WITHOUT JUDGING."
  ]},

  { title: "FRICTION", lines: [
    "SURFACES RUB.",
    "HEAT REVEALS THE SHAPE OF INTENTION.",
    "WHAT IRRITATES MAY ALSO POLISH."
  ]},

  { title: "ROAR", lines: [
    "VOICE OVERPOWERS FEAR.",
    "SOUND BURSTS THROUGH HESITATION.",
    "COURAGE IS VOLUME MADE AUDIBLE."
  ]},

  { title: "LIFT-OFF", lines: [
    "GRAVITY RELENTS.",
    "ASSUMPTIONS LOOSEN THEIR HOLD.",
    "ASCENT BEGINS WITH LIGHTNESS."
  ]},

  { title: "FLOW", lines: [
    "RESISTANCE FORGETS YOUR NAME.",
    "TIME DISSOLVES INTO MOTION.",
    "YOU ARE CARRIED BY THE CURRENT YOU ARE."
  ]},

  { title: "QUENCH", lines: [
    "HEAT MEETS COOL.",
    "INTENSITY TEMPERED INTO STRENGTH.",
    "RESTORES SHAPE WITHOUT BREAKING."
  ]},

  { title: "FOCUS", lines: [
    "LIGHT BEAMS NARROW.",
    "ATTENTION BURNS CLEAN THROUGH NOISE.",
    "ONE AIM, MANY CONSEQUENCES."
  ]},

  { title: "FORGE", lines: [
    "PRESSURE CREATES FORM.",
    "STRESS SHAPES CAPACITY.",
    "OBSTACLES ARE TOOLS IN DISGUISE."
  ]},

  { title: "FLIGHT", lines: [
    "SPEED LEAVES DOUBT BEHIND.",
    "ACTION OUTRUNS FEAR.",
    "THE AIR HOLDS YOU LONGER THAN YOU THINK."
  ]},

  { title: "ORBIT", lines: [
    "DISTANCE PRESERVES PERSPECTIVE.",
    "CIRCLES HOLD CONNECTION WITHOUT MERGE.",
    "SEE CLEARER FROM A STEP AWAY."
  ]},

  { title: "DRUM", lines: [
    "RHYTHM ANCHORS COMMUNITY.",
    "A BEAT HOLDS MANY TOGETHER.",
    "STEADINESS IS SERVICE."
  ]},

  { title: "SHIELD", lines: [
    "PROTECTION WITHOUT ISOLATION.",
    "BOUNDARY DOES NOT MEAN WALL.",
    "SAFETY CAN BE TRANSPARENT."
  ]},

  { title: "CRACKLE", lines: [
    "STATIC ANNOUNCES POSSIBILITY.",
    "THE FIELD HISSES BEFORE IGNITION.",
    "LISTEN TO THE BUZZ OF ARRIVAL."
  ]},

  { title: "BLAZE", lines: [
    "BURN SO THE PATH APPEARS.",
    "INTENSE LIGHT REVEALS DIRECTION.",
    "OTHERS FOLLOW YOUR FIRE."
  ]},

  { title: "CLASH", lines: [
    "CONFRONTATION ARRIVES INEVITABLE.",
    "ENERGY COLLIDES TO REVEAL TRUTH.",
    "HONEST IMPACT CLEARS THE AIR."
  ]},

  { title: "SHATTER", lines: [
    "OLD STRUCTURE BREAKS.",
    "THE SHELL CANNOT HOLD.",
    "FREEDOM EMERGES FROM SPLINTERS."
  ]},

  { title: "OVERFLOW", lines: [
    "EXCESS SPILLS OUTWARD.",
    "SURPLUS BECOMES GIFT.",
    "ABUNDANCE SEEKS CIRCULATION."
  ]},

  { title: "SPIRAL", lines: [
    "ASCENT TURNS INWARD AND OUTWARD.",
    "CYCLES RISE BY ROTATION.",
    "GROWTH IS NEVER A STRAIGHT LINE."
  ]},

  { title: "STOKE", lines: [
    "FUEL THE FIRE.",
    "COMMUNAL FLAME BRIGHTENS WITH YOUR OFFERING.",
    "ENERGY MULTIPLIES WHEN SHARED."
  ]},

  { title: "QUAKE", lines: [
    "FOUNDATION SHIFTS.",
    "BELIEFS TREMBLE INTO NEW LANDSCAPES.",
    "SOFT KNEES SURVIVE THE SHAKE."
  ]},

  { title: "PIERCE", lines: [
    "THE VEIL SPLITS.",
    "HIDDEN TRUTH DEMANDS ENTRY.",
    "SHARPNESS REVEALS ESSENCE."
  ]},

  { title: "WHITE HEAT", lines: [
    "GLOW BEYOND COLOR.",
    "INTENSITY REFINES INTO CLARITY.",
    "PURE PURPOSE LEAVES ONLY LIGHT."
  ]},

  { title: "RUPTURE", lines: [
    "THE WALL CRACKS OPEN.",
    "FISSURE BECOMES PORTAL.",
    "PASS THROUGH OR REMAIN DIVIDED."
  ]},

  { title: "CLARITY", lines: [
    "VISION STEADIES.",
    "FOG FALLS AWAY.",
    "THE EYE THAT NEVER BLINKS SEES."
  ]},

  { title: "STILL FLAME", lines: [
    "BURN WITHOUT CONSUMING.",
    "FIRE THAT DOES NOT WASTE.",
    "STEADY HEAT IS SUSTAINABLE LIGHT."
  ]},

  { title: "RESONANCE", lines: [
    "VIBRATION MATCHES VIBRATION.",
    "FREQUENCIES JOIN WITHOUT EFFORT.",
    "HARMONY IS SIGNAL RECOGNITION."
  ]},

  { title: "VISION", lines: [
    "IMAGE TOO WIDE FOR LANGUAGE.",
    "MIND STRETCHED TO RECEIVE.",
    "SEEING IS ALSO BECOMING."
  ]},

  { title: "GRACEFALL", lines: [
    "DESCENT CAN BE SOFT.",
    "FALLING IS NOT FAILURE.",
    "GRACE CUSHIONS THE DROP."
  ]},

  { title: "SYNTHESIS", lines: [
    "OPPOSITES COMPLETE EACH OTHER.",
    "TENSION PRODUCES NEW FORM.",
    "INTEGRATION IS INVENTION."
  ]},

  { title: "GLIMPSE", lines: [
    "PATTERN REVEALS ITSELF.",
    "MOTIFS RETURN IN CYCLES.",
    "SEEING CONNECTION IS SEEING DESIGN."
  ]},

  { title: "BEACON", lines: [
    "SHINE SO OTHERS RECALL ORIGIN.",
    "GUIDANCE IS LIGHT VISIBLE FROM FAR.",
    "YOUR PRESENCE REMINDS THEM HOME."
  ]},

  { title: "TRANSLUCENCE", lines: [
    "LIGHT PASSES THROUGH STORY.",
    "TRANSPARENCY INVITES SHARED SEEING.",
    "CLEARNESS IS COURAGE."
  ]},

  { title: "LATTICE", lines: [
    "INVISIBLE GRIDS HOLD FORM.",
    "STRUCTURES BENEATH SURFACES GUIDE.",
    "CONNECTIONS ARE THE HIDDEN FRAME."
  ]},

  { title: "MERGE", lines: [
    "JOIN WITHOUT ERASURE.",
    "UNITY CAN PRESERVE OUTLINE.",
    "TOGETHER AND DISTINCT."
  ]},

  { title: "ECHELON", lines: [
    "STAND ON A HIGHER TERRACE.",
    "SEE TIME FROM ALTITUDE.",
    "PERSPECTIVE REWRITES THE PRESENT."
  ]},

  { title: "HUSH", lines: [
    "SILENCE BEYOND WORDS.",
    "QUIET REVEALS MEANING.",
    "ABSENCE SPEAKS THE LOUDEST."
  ]},

  { title: "WEIGHTLESSNESS", lines: [
    "FLOAT ABOVE MEASURE.",
    "JUDGMENT RELEASES ITS GRIP.",
    "LIGHTNESS BECOMES YOUR ELEMENT."
  ]},

  { title: "IRIS", lines: [
    "BOUNDARIES AS LENSES.",
    "APERTURE CONTROLS LIGHT.",
    "SEE DIFFERENTLY BY SHIFTING THE OPENING."
  ]},

  { title: "BREATHLESS", lines: [
    "THE GAP HOLDS PRESENCE.",
    "SUSPENSION IS ALIVE.",
    "BETWEEN INHALE AND EXHALE, TRUTH APPEARS."
  ]},

  { title: "PULSEWAVE", lines: [
    "THE UNIVERSE THROBS INSIDE YOU.",
    "YOUR BEAT ECHOES THE COSMOS.",
    "MERGE WITH THE GREATER RHYTHM."
  ]},

  { title: "APERTURE", lines: [
    "OPENING WITHOUT DOOR.",
    "THE HEART EXPANDS LIKE A LENS.",
    "ALLOWING IS ENTRY."
  ]},

  { title: "NADIR ZENITH", lines: [
    "LOWEST AND HIGHEST EXIST TOGETHER.",
    "CYCLE HOLDS BOTH PEAK AND VALLEY.",
    "THE ARC IS YOUR CONTAINER."
  ]},

  { title: "CRYSTAL", lines: [
    "PURE INTENTION HARDENS TO FORM.",
    "FACETS MULTIPLY LIGHT.",
    "CLARITY IS STRUCTURE."
  ]},

  { title: "MIRRORLESS", lines: [
    "REFLECTION REMOVED.",
    "SEE THE WORLD WITHOUT SELF-REFERENCE.",
    "REALITY ARRIVES UNFILTERED."
  ]},

  { title: "SOURCE TOUCH", lines: [
    "NOTHING REMAINS BUT PULSE.",
    "SILENCE AS MIRROR.",
    "YOU ARE THE CODE ITSELF."
  ]}

];
